package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"strings"
	"syscall"
)

// generatedConfigFile holds the Match blocks written by `jumper sync`.
const generatedConfigFile = "/etc/ssh/sshd_config.d/jumper-generated.conf"

// runSync implements `jumper sync`: regenerate the rules and reload sshd.
func runSync(args []string) error {
	if len(args) != 0 {
		return errors.New("usage: jumper sync")
	}
	return syncConfig(true)
}

// syncConfig writes the Match blocks for the current hosts file, validates
// them with `sshd -t` (restoring the previous file on failure) and, if reload
// is set, tells the running sshd (PID 1) to reload.
func syncConfig(reload bool) error {
	hosts, err := readHosts()
	if err != nil {
		return err
	}
	path := at(generatedConfigFile)
	previous, err := os.ReadFile(path)
	hadPrevious := err == nil
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}

	if err := writeFileAtomic(path, []byte(generateConfig(hosts)), 0o644); err != nil {
		return err
	}
	if err := checkSshdConfig(); err != nil {
		if hadPrevious {
			_ = writeFileAtomic(path, previous, 0o644)
		} else {
			_ = os.Remove(path)
		}
		return fmt.Errorf("generated config rejected, previous rules kept: %w", err)
	}

	// Only reload inside the container; with JUMPER_ROOT (tests) PID 1 is not sshd.
	if reload && root == "/" {
		if err := syscall.Kill(1, syscall.SIGHUP); err != nil {
			return fmt.Errorf("reloading sshd: %w", err)
		}
	}
	fmt.Fprintf(os.Stderr, "jumper sync: %d host(s) configured\n", len(hosts))
	return nil
}

// generateConfig renders the sshd Match blocks: one per host account
// (reverse tunnel on its own port) and one for all persons (ProxyJump to
// the tunnel ports, menu with agent forwarding).
func generateConfig(hosts []*hostEntry) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `jumper sync` from %s - do not edit.\n\n", hostsFile)

	var permitOpen []string
	for _, h := range hosts {
		fmt.Fprintf(&b, "Match User %s Group hosts\n", h.Name)
		b.WriteString("    AllowTcpForwarding remote\n")
		fmt.Fprintf(&b, "    PermitListen %d\n\n", h.Port)
		permitOpen = append(permitOpen, fmt.Sprintf("localhost:%d 127.0.0.1:%d", h.Port, h.Port))
	}
	if len(permitOpen) == 0 {
		permitOpen = []string{"none"}
	}

	b.WriteString("Match Group persons\n")
	b.WriteString("    AllowTcpForwarding local\n")
	fmt.Fprintf(&b, "    PermitOpen %s\n", strings.Join(permitOpen, " "))
	b.WriteString("    AllowAgentForwarding yes\n")
	b.WriteString("    PermitTTY yes\n")
	return b.String()
}

// checkSshdConfig runs `sshd -t`. Outside the container (no sshd under
// root) the check is skipped with a warning.
func checkSshdConfig() error {
	sshd := at(sshdBinary)
	if _, err := os.Stat(sshd); err != nil {
		fmt.Fprintf(os.Stderr, "jumper: %s not found, skipping config test\n", sshdBinary)
		return nil
	}
	if out, err := exec.Command(sshd, "-t").CombinedOutput(); err != nil {
		return fmt.Errorf("sshd -t: %v\n%s", err, out)
	}
	return nil
}

// writeFileAtomic replaces path with data via a temporary file and rename,
// so readers never see a half-written file.
func writeFileAtomic(path string, data []byte, perm fs.FileMode) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	if err := os.Chmod(tmp, perm); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
